from PyQt5 import QtCore, QtGui, QtWidgets

class AccountTab(QtWidgets.QWidget):
    def __init__(self):
        super(AccountTab, self).__init__()
 
        self.setObjectName("tab_5")
        self.listWidget_16 = QtWidgets.QListWidget(self)
        self.listWidget_16.setGeometry(QtCore.QRect(10, 60, 771, 441))
        self.listWidget_16.setObjectName("listWidget_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self)
        self.lineEdit_17.setGeometry(QtCore.QRect(10, 20, 255, 31))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.widget_9 = QtWidgets.QWidget(self)
        self.widget_9.setGeometry(QtCore.QRect(20, 80, 741, 61))
        self.widget_9.setObjectName("widget_9")
        self.label_68 = QtWidgets.QLabel(self.widget_9)
        self.label_68.setGeometry(QtCore.QRect(30, 10, 131, 16))
        self.label_68.setObjectName("label_68")
        self.pushButton_45 = QtWidgets.QPushButton(self.widget_9)
        self.pushButton_45.setGeometry(QtCore.QRect(500, 0, 100, 41))
        self.pushButton_45.setObjectName("pushButton_45")
        self.label_70 = QtWidgets.QLabel(self.widget_9)
        self.label_70.setGeometry(QtCore.QRect(30, 30, 111, 16))
        self.label_70.setObjectName("label_70")
        self.label_69 = QtWidgets.QLabel(self.widget_9)
        self.label_69.setGeometry(QtCore.QRect(210, 30, 58, 16))
        self.label_69.setObjectName("label_69")
        self.label_67 = QtWidgets.QLabel(self.widget_9)
        self.label_67.setGeometry(QtCore.QRect(120, 30, 81, 16))
        self.label_67.setObjectName("label_67")
        self.pushButton_46 = QtWidgets.QPushButton(self.widget_9)
        self.pushButton_46.setGeometry(QtCore.QRect(620, 0, 100, 41))
        self.pushButton_46.setObjectName("pushButton_46")
        self.checkBox = QtWidgets.QCheckBox(self.widget_9)
        self.checkBox.setGeometry(QtCore.QRect(10, 10, 21, 20))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.pushButton_47 = QtWidgets.QPushButton(self)
        self.pushButton_47.setGeometry(QtCore.QRect(680, 20, 100, 41))
        self.pushButton_47.setObjectName("pushButton_47")
        self.pushButton_48 = QtWidgets.QPushButton(self)
        self.pushButton_48.setGeometry(QtCore.QRect(570, 20, 100, 41))
        self.pushButton_48.setObjectName("pushButton_48")
        self.pushButton_49 = QtWidgets.QPushButton(self)
        self.pushButton_49.setGeometry(QtCore.QRect(460, 20, 100, 41))
        self.pushButton_49.setObjectName("pushButton_49")