from PyQt5 import QtCore, QtGui, QtWidgets

class AccountTab(QtWidgets.QWidget):
    def __init__(self):
        super(AccountTab, self).__init__()
 
        self.setObjectName("tab_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_4 = QtWidgets.QWidget(self)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.horizontalLayout_5.addWidget(self.lineEdit_24)
        self.frame_6 = QtWidgets.QFrame(self.widget_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5.addWidget(self.frame_6)
        self.pushButton_64 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_64.setObjectName("pushButton_64")
        self.horizontalLayout_5.addWidget(self.pushButton_64)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 2)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout_7.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.horizontalLayout_6.addWidget(self.lineEdit_23)
        self.frame_5 = QtWidgets.QFrame(self.widget_5)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_6.addWidget(self.frame_5)
        self.pushButton_69 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_69.setObjectName("pushButton_69")
        self.horizontalLayout_6.addWidget(self.pushButton_69)
        self.pushButton_68 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_68.setObjectName("pushButton_68")
        self.horizontalLayout_6.addWidget(self.pushButton_68)
        self.pushButton_65 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_65.setObjectName("pushButton_65")
        self.horizontalLayout_6.addWidget(self.pushButton_65)
        self.horizontalLayout_6.setStretch(0, 2)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout_7.addWidget(self.widget_5)
        self.widget_13 = QtWidgets.QWidget(self)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget_13)
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_7.addWidget(self.checkBox_3)
        self.label_85 = QtWidgets.QLabel(self.widget_13)
        self.label_85.setObjectName("label_85")
        self.horizontalLayout_7.addWidget(self.label_85)
        self.label_84 = QtWidgets.QLabel(self.widget_13)
        self.label_84.setObjectName("label_84")
        self.horizontalLayout_7.addWidget(self.label_84)
        self.label_87 = QtWidgets.QLabel(self.widget_13)
        self.label_87.setObjectName("label_87")
        self.horizontalLayout_7.addWidget(self.label_87)
        self.pushButton_66 = QtWidgets.QPushButton(self.widget_13)
        self.pushButton_66.setObjectName("pushButton_66")
        self.horizontalLayout_7.addWidget(self.pushButton_66)
        self.pushButton_67 = QtWidgets.QPushButton(self.widget_13)
        self.pushButton_67.setObjectName("pushButton_67")
        self.horizontalLayout_7.addWidget(self.pushButton_67)
        self.verticalLayout_7.addWidget(self.widget_13)
        self.listWidget_22 = QtWidgets.QListWidget(self)
        self.listWidget_22.setObjectName("listWidget_22")
        self.verticalLayout_7.addWidget(self.listWidget_22)