from PyQt5 import QtCore, QtGui, QtWidgets

class AddProgramTab(QtWidgets.QWidget):
    def __init__(self):
        super(AddProgramTab, self).__init__()

        self.setObjectName("AddProgramTab")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.widget_8 = QtWidgets.QWidget(self)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_8)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_32.addWidget(self.lineEdit_3)
        self.listWidget_2 = QtWidgets.QListWidget(self.widget_8)
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_32.addWidget(self.listWidget_2)
        self.pushButton_12 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_32.addWidget(self.pushButton_12)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_32.addWidget(self.pushButton_11)
        self.horizontalLayout_19.addWidget(self.widget_8)
        self.widget_11 = QtWidgets.QWidget(self)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_33.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget_11)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_2.addWidget(self.lineEdit_11, 0, 0, 1, 1)
        self.graphicsView_12 = QtWidgets.QGraphicsView(self.widget_11)
        self.graphicsView_12.setObjectName("graphicsView_12")
        self.gridLayout_2.addWidget(self.graphicsView_12, 1, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget_11)
        self.pushButton_10.setEnabled(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_2.addWidget(self.pushButton_10, 9, 0, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.widget_11)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_2.addWidget(self.lineEdit_12, 2, 0, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.listWidget_24 = QtWidgets.QListWidget(self.widget_11)
        self.listWidget_24.setObjectName("listWidget_24")
        self.horizontalLayout_23.addWidget(self.listWidget_24)
        self.checkBox_9 = QtWidgets.QCheckBox(self.widget_11)
        self.checkBox_9.setObjectName("checkBox_9")
        self.horizontalLayout_23.addWidget(self.checkBox_9)
        self.checkBox_8 = QtWidgets.QCheckBox(self.widget_11)
        self.checkBox_8.setObjectName("checkBox_8")
        self.horizontalLayout_23.addWidget(self.checkBox_8)
        self.gridLayout_2.addLayout(self.horizontalLayout_23, 8, 0, 1, 1)
        self.frame_16 = QtWidgets.QFrame(self.widget_11)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_2.addWidget(self.frame_16, 10, 0, 1, 1)
        self.dateTimeEdit_4 = QtWidgets.QDateTimeEdit(self.widget_11)
        self.dateTimeEdit_4.setObjectName("dateTimeEdit_4")
        self.gridLayout_2.addWidget(self.dateTimeEdit_4, 4, 0, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.widget_11)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_2.addWidget(self.lineEdit_13, 5, 0, 1, 1)
        self.pushButton_29 = QtWidgets.QPushButton(self.widget_11)
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout_2.addWidget(self.pushButton_29, 3, 0, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_102 = QtWidgets.QLabel(self.widget_11)
        self.label_102.setObjectName("label_102")
        self.horizontalLayout_21.addWidget(self.label_102)
        self.listView_5 = QtWidgets.QListView(self.widget_11)
        self.listView_5.setObjectName("listView_5")
        self.horizontalLayout_21.addWidget(self.listView_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_21, 6, 0, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_103 = QtWidgets.QLabel(self.widget_11)
        self.label_103.setObjectName("label_103")
        self.horizontalLayout_22.addWidget(self.label_103)
        self.checkBox_22 = QtWidgets.QCheckBox(self.widget_11)
        self.checkBox_22.setObjectName("checkBox_22")
        self.horizontalLayout_22.addWidget(self.checkBox_22)
        self.pushButton_88 = QtWidgets.QPushButton(self.widget_11)
        self.pushButton_88.setObjectName("pushButton_88")
        self.horizontalLayout_22.addWidget(self.pushButton_88)
        self.gridLayout_2.addLayout(self.horizontalLayout_22, 7, 0, 1, 1)
        self.verticalLayout_33.addLayout(self.gridLayout_2)
        self.horizontalLayout_19.addWidget(self.widget_11)

        # Text
        self.pushButton_29.setText("Add Image")
        self.pushButton_12.setText("Remove")
        self.pushButton_11.setText("Add")
        self.label_102.setText("Department")
        self.label_103.setText("Participants")
        self.checkBox_22.setText("Select All")
        self.pushButton_88.setText("Remove")
        self.checkBox_8.setText("Username")
        self.pushButton_10.setText("Save")
        self.lineEdit_3.setPlaceholderText("Search")
        